### ISSUE TITLE
Help implementing this plugin

### ISSUE THREAD

**Issue by alonmalka** [Nicnl/homebridge-minimal-http-blinds#1]
When I run this plug in I get  "error when pulling current state/ position"
This is because I don't know how to send back a value.
I use homebridge on Win 7. Can someone help? I guess I have to create some kind of a server that stores the values but I don't know how.
I use Evenghost if this might help.

Thanks Guys,

Alon

**Comment by Nicnl** [comment]
I'm not sure what _Evenghost_ is to be honnest.

I just wrote for you an example implementation in Python of the server you need.
https://github.com/Nicnl/homebridge-minimal-http-blinds/blob/master/EXAMPLE.MD

**Comment by Nicnl** [comment]
Hey @alonmalka  
Is your issue resolved?  
It it is, I'd like to mark this issue as resolved and close it.

**Comment by alonmalka** [comment]
Hi,

Yes thanks.
Go ahead and mark it as resolved.

Thanks again.

Alon

נשלח מה-iPhone שלי

‫ב-4 באפר׳ 2018, בשעה 13:47, ‏‏Nicnl ‏<notifications@github.com> כתב/ה:‬
